### ISSUE TITLE
When will any of these samples use published Nuget packages?

### ISSUE THREAD

**Issue by Noemata** [webrtc-uwp/PeerCC-XPlatform#1]
For quite some time now, none of the samples have used published Nuget packages, which is the way the WebRTC lib should be consumed.

Please publish samples that use nuget packages rather than deep links into a specific repo structure.

**Comment by ghost** [comment]
@Noemata 
This sample used nuget at first, but I had issues debugging it that way that's why webrtc-uwp-sdk is used at the moment to reference WebRtc. It's not problem to change it to reference nuget any time.

**Comment by Noemata** [comment]
Samples that are provided for general consumption should only use nuget packages.  If you need to debug, then create a repo just for that.  Master shouldn't be used for debugging what should be a stable release.

Also it's not obvious what version of the repo you may be pulling from.

As it stands, there isn't a single sample on GitHub that uses any of the newer WebRTC nuget releases.

**Comment by robin-raymond** [comment]
@Noemata Generally I agree but this sample isn't ready for prime time yet but it's going to happen soon. We are also planning to have two projects, one for nuget and one for the building/debugging.

**Comment by Noemata** [comment]
Please provide at least one working UWP sample that uses the newer nuget packages.  I ask because I haven't been able to get to a working state with the most recent nuget packages due to missing API references.  I can hobble some of those together by pulling from parts of the repos here, but it's becoming progressively harder to figure out what to pull from given all the different branches available.

Seeing things like:

`<HintPath>..\..\..\..\..\ortc\windows\solutions\$(PlatformTarget)\$(Configuration)\Org.Ortc\Org.Ortc.Adapter.winmd</HintPath>`

in the various projects files is painful because you realize you need to know exactly how to layout the source to get things to build.  Nuget obviates this sort of thing.  @robin-raymond I think you would agree the current sample solutions are not self contained.  Nuget packages resolve this problem.

There is a reason there are so few downloads of recent nuget releases.  There's no working sample and without it, it has become tedious to get things to build because of what's currently missing in the nuget packages provided.

**Comment by ghost** [comment]
Sample uses published NuGet package.
