### ISSUE TITLE
Coding style.

### ISSUE THREAD

**Issue by Noemata** [webrtc-uwp/PeerCC-XPlatform#2]
Please try to limit the degree to which aspects of this code become obfuscated.

Example:

Regex mfdRegex = new Regex("\r\nm=audio.*RTP.*?( .\\d*)+\r\n");

Could be:

private const string ExtractAudioRegEx = "\r\nm=audio.*RTP.*?( .\\d*)+\r\n";
…
Regex mfdRegex = new Regex(ExtractAudioRegEx);

etc.

Some of the code files are too discrete.  Lots of code files with a few lines of code obfuscate discovery.

**Comment by ghost** [comment]
@Noemata 
Thanks for your suggestion, this sample is not finished yet. 
Code you mentioned here is borrowed from previous sample but it's currently commented out, so it will be changed.

**Comment by Noemata** [comment]
Thank you for the clarification.
